In [4]:
import sys
sys.path.insert(0, '../')
import fconcrete as fc
import numpy as np
#plt.rcParams["figure.figsize"] = (25,10)

In [5]:
def concrete_beam_function(width, height, length):
    
    n1 = fc.Node.SimpleSupport(x=0, length=20)
    n2 = fc.Node.SimpleSupport(x=length, length=20)

    slab_area = 5*5
    kn_per_m2 = 5
    distributed_load = -slab_area*kn_per_m2/500
    f1 = fc.Load.UniformDistributedLoad(distributed_load, x_begin=0, x_end=length)
    pp = fc.Load.UniformDistributedLoad(-width*height*25/100000, x_begin=0, x_end=length)

    beam = fc.ConcreteBeam(
        loads = [f1, pp],
        nodes = [n1, n2],
        section = fc.Rectangle(width,height),
        bar_steel_max_removal = 100,
        transversal_bar_inclination_angle=90,
        available_long_steel_bars = fc.AvailableLongConcreteSteelBar(diameters=[8], max_number=500),
        available_transv_steel_bars = fc.AvailableTransvConcreteSteelBar(diameters=[6.3], space_is_multiple_of=[1]),
        available_concrete = fc.AvailableConcrete(fck=30, aggressiveness=2),
        solve_transv_steel = True,
        solve_long_steel = True,
        solve_ELS = True,
        solve_cost = True,
        verbose = False,
    )
    
    return beam

In [14]:
concrete_beam = concrete_beam_function(15, 30, 200)

In [15]:
self = concrete_beam.long_steel_bars_solution_info

In [55]:
min_area, max_area = self.getMinimumAndMaximumSteelArea(0)
area = self.getSteelArea(0, 20)

In [58]:
x, momentum = 0, 20

In [67]:
self.getSteelArea(0, 20)

0.019178861424072494

In [75]:
0.15*450/100

0.675

In [69]:
_, beam_element = self.concrete_beam.getBeamElementInX(0)

In [76]:
beam_element.material.fck

3.0

In [79]:
fck=3
area=450

In [80]:
fck_array = 20 + 5*np.arange(15)
fck_array = fck_array/10
p_min_array = np.array([ 0.115, 0.115, 0.115, 0.1164, 0.179, 0.194, 0.208, 0.211, 0.219, 0.226, 0.233, 0.239, 0.245, 0.251, 0.256])
p_min = np.interp(fck, fck_array, p_min_array)
A_min = area*p_min/100
A_max = 0.008*area

In [84]:
fck_array

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. ])

In [86]:
np.interp(fck, fck_array, p_min_array)

1.15

In [89]:
A_min, A_max

(5.175, 3.6)

In [77]:
fc.LongSteelBar.getMinimumAndMaximumSteelArea(
            area = 450,
            fck = 3
        )

(5.175, 3.6)

In [ ]:
min_area, max_area = self.getMinimumAndMaximumSteelArea(x)

In [61]:
min_area, max_area = self.getMinimumAndMaximumSteelArea(x)
area = self.getSteelArea(x, momentum)

# Implement minimun area in support

if abs(area)>max_area: raise Exception("Too much steel needed in x={}, area needed is {}cmˆ2, but the maximum is {}cmˆ2".format(x, abs(area), max_area))

if np.isnan(area): v = np.repeat(np.nan, 3)
if area>0 :
    area = max(min_area, area)
    possible_areas = self.available.table[:,2] > area
    if len(possible_areas)==0: raise Exception("There is not a possible available longitudinal steel bar. You should try to increase max_number of fc.AvailableLongConcreteSteelBar.")
    values = self.available.table[possible_areas][0]
else:
    possible_areas = self.available.table[:,2] < area
    if len(possible_areas)==0: raise Exception("There is not a possible available longitudinal steel bar. You should try to increase max_number of fc.AvailableLongConcreteSteelBar.")
    values = self.available.table[possible_areas][-1]
quantity, diameter, area = values
v = quantity, diameter, area

In [65]:
area

5.5

In [64]:
for row in self.available.table:
    print(row)

[ 500.    -0.8 -250. ]
[ 499.    -0.8 -249.5]
[ 498.    -0.8 -249. ]
[ 497.    -0.8 -248.5]
[ 496.    -0.8 -248. ]
[ 495.    -0.8 -247.5]
[ 494.    -0.8 -247. ]
[ 493.    -0.8 -246.5]
[ 492.    -0.8 -246. ]
[ 491.    -0.8 -245.5]
[ 490.    -0.8 -245. ]
[ 489.    -0.8 -244.5]
[ 488.    -0.8 -244. ]
[ 487.    -0.8 -243.5]
[ 486.    -0.8 -243. ]
[ 485.    -0.8 -242.5]
[ 484.    -0.8 -242. ]
[ 483.    -0.8 -241.5]
[ 482.    -0.8 -241. ]
[ 481.    -0.8 -240.5]
[ 480.    -0.8 -240. ]
[ 479.    -0.8 -239.5]
[ 478.    -0.8 -239. ]
[ 477.    -0.8 -238.5]
[ 476.    -0.8 -238. ]
[ 475.    -0.8 -237.5]
[ 474.    -0.8 -237. ]
[ 473.    -0.8 -236.5]
[ 472.    -0.8 -236. ]
[ 471.    -0.8 -235.5]
[ 470.    -0.8 -235. ]
[ 469.    -0.8 -234.5]
[ 468.    -0.8 -234. ]
[ 467.    -0.8 -233.5]
[ 466.    -0.8 -233. ]
[ 465.    -0.8 -232.5]
[ 464.    -0.8 -232. ]
[ 463.    -0.8 -231.5]
[ 462.    -0.8 -231. ]
[ 461.    -0.8 -230.5]
[ 460.    -0.8 -230. ]
[ 459.    -0.8 -229.5]
[ 458.    -0.8 -229. ]
[ 457.    -

[ 35.   -0.8 -17.5]
[ 34.   -0.8 -17. ]
[ 33.   -0.8 -16.5]
[ 32.   -0.8 -16. ]
[ 31.   -0.8 -15.5]
[ 30.   -0.8 -15. ]
[ 29.   -0.8 -14.5]
[ 28.   -0.8 -14. ]
[ 27.   -0.8 -13.5]
[ 26.   -0.8 -13. ]
[ 25.   -0.8 -12.5]
[ 24.   -0.8 -12. ]
[ 23.   -0.8 -11.5]
[ 22.   -0.8 -11. ]
[ 21.   -0.8 -10.5]
[ 20.   -0.8 -10. ]
[19.  -0.8 -9.5]
[18.  -0.8 -9. ]
[17.  -0.8 -8.5]
[16.  -0.8 -8. ]
[15.  -0.8 -7.5]
[14.  -0.8 -7. ]
[13.  -0.8 -6.5]
[12.  -0.8 -6. ]
[11.  -0.8 -5.5]
[10.  -0.8 -5. ]
[ 9.  -0.8 -4.5]
[ 8.  -0.8 -4. ]
[ 7.  -0.8 -3.5]
[ 6.  -0.8 -3. ]
[ 5.  -0.8 -2.5]
[ 4.  -0.8 -2. ]
[ 3.  -0.8 -1.5]
[ 2.  -0.8 -1. ]
[2.  0.8 1. ]
[3.  0.8 1.5]
[4.  0.8 2. ]
[5.  0.8 2.5]
[6.  0.8 3. ]
[7.  0.8 3.5]
[8.  0.8 4. ]
[9.  0.8 4.5]
[10.   0.8  5. ]
[11.   0.8  5.5]
[12.   0.8  6. ]
[13.   0.8  6.5]
[14.   0.8  7. ]
[15.   0.8  7.5]
[16.   0.8  8. ]
[17.   0.8  8.5]
[18.   0.8  9. ]
[19.   0.8  9.5]
[20.   0.8 10. ]
[21.   0.8 10.5]
[22.   0.8 11. ]
[23.   0.8 11.5]
[24.   0.8 12. ]
[25.   

[413.    0.8 206.5]
[414.    0.8 207. ]
[415.    0.8 207.5]
[416.    0.8 208. ]
[417.    0.8 208.5]
[418.    0.8 209. ]
[419.    0.8 209.5]
[420.    0.8 210. ]
[421.    0.8 210.5]
[422.    0.8 211. ]
[423.    0.8 211.5]
[424.    0.8 212. ]
[425.    0.8 212.5]
[426.    0.8 213. ]
[427.    0.8 213.5]
[428.    0.8 214. ]
[429.    0.8 214.5]
[430.    0.8 215. ]
[431.    0.8 215.5]
[432.    0.8 216. ]
[433.    0.8 216.5]
[434.    0.8 217. ]
[435.    0.8 217.5]
[436.    0.8 218. ]
[437.    0.8 218.5]
[438.    0.8 219. ]
[439.    0.8 219.5]
[440.    0.8 220. ]
[441.    0.8 220.5]
[442.    0.8 221. ]
[443.    0.8 221.5]
[444.    0.8 222. ]
[445.    0.8 222.5]
[446.    0.8 223. ]
[447.    0.8 223.5]
[448.    0.8 224. ]
[449.    0.8 224.5]
[450.    0.8 225. ]
[451.    0.8 225.5]
[452.    0.8 226. ]
[453.    0.8 226.5]
[454.    0.8 227. ]
[455.    0.8 227.5]
[456.    0.8 228. ]
[457.    0.8 228.5]
[458.    0.8 229. ]
[459.    0.8 229.5]
[460.    0.8 230. ]
[461.    0.8 230.5]
[462.    0.8 231. ]


In [16]:
positive_areas_info = self.positive_areas_info
interspace_between_momentum_positive = self.interspace_between_momentum_positive
negative_areas_info = self.negative_areas_info
interspace_between_momentum_negative = self.interspace_between_momentum_negative
x = self.x

In [52]:
positive_areas_info

array([[11. , 11. , 11. , ..., 11. , 11. , 11. ],
       [ 0.8,  0.8,  0.8, ...,  0.8,  0.8,  0.8],
       [ 5.5,  5.5,  5.5, ...,  5.5,  5.5,  5.5]])

In [11]:

steel_bars_positive = self._getBarsInInterspaces(x, positive_areas_info, interspace_between_momentum_positive)
steel_bars_negative = self._getBarsInInterspaces(x, negative_areas_info, interspace_between_momentum_negative)


NameError: name 'verbose' is not defined

In [41]:
positive_areas_info

array([[11. , 11. , 11. , ..., 11. , 11. , 11. ],
       [ 0.8,  0.8,  0.8, ...,  0.8,  0.8,  0.8],
       [ 5.5,  5.5,  5.5, ...,  5.5,  5.5,  5.5]])

In [42]:
interspace_between_momentum_positive

array([[-11.99999, 211.99999]])

In [30]:
LongSteelBars = fc.LongSteelBars
LongSteelBar = fc.LongSteelBar

In [43]:
x, areas_info, interspaceBetweenMomentum = x, positive_areas_info, interspace_between_momentum_positive

In [51]:
areas_info

array([[11. , 11. , 11. , ..., 11. , 11. , 11. ],
       [ 0.8,  0.8,  0.8, ...,  0.8,  0.8,  0.8],
       [ 5.5,  5.5,  5.5, ...,  5.5,  5.5,  5.5]])

In [44]:

quantities, diameters, _ = areas_info  
bar_steel_removal_step = self.bar_steel_removal_step
bar_steel_max_removal = self.bar_steel_max_removal

bars = LongSteelBars()
for interspace in interspaceBetweenMomentum:
    bars_interspace = LongSteelBars()
    times_removal_occurred = 0

    #commum interspace info
    interspace_start, interspace_end = interspace[0], interspace[1]
    is_in_interpace = (x > interspace_start) & (x<interspace_end)
    x_interspace = x[is_in_interpace]
    quantities_interspace = quantities[is_in_interpace]
    diameter = diameters[is_in_interpace][0]

    max_quantity_interspace = int(max(quantities_interspace))
    min_quantity_interspace = int(min(quantities_interspace))

    for quantity in range(1, max_quantity_interspace+1):
        if np.isin(quantity, bars_interspace.quantities_accumulated): continue
        x_same_quantity = x_interspace[quantities_interspace == quantity]
        if len(x_same_quantity)>0:
            # Just removing bars according to bar_steel_removal_step
            reminder = (quantity-min_quantity_interspace)%bar_steel_removal_step
            quantity_accumulated = min(quantity - reminder + (reminder>0)*self.bar_steel_removal_step, max_quantity_interspace)
            new_reminder = (quantity_accumulated-min_quantity_interspace)%bar_steel_removal_step
            new_quantity = bar_steel_removal_step-new_reminder if min_quantity_interspace!=quantity_accumulated else min_quantity_interspace

            removal_limit_reached = times_removal_occurred>=bar_steel_max_removal-1


            quantity = new_quantity if not removal_limit_reached else new_quantity+max_quantity_interspace-quantity_accumulated
            quantity_accumulated = quantity_accumulated if not removal_limit_reached else max_quantity_interspace

            area_accumulated = self.available.diameters_to_area[abs(diameter*10)]*quantity_accumulated*(1 if diameter>0 else -1)
            fyd = self.available.fyd
            area = self.available.diameters_to_area[abs(diameter*10)]*quantity*(1 if diameter>0 else -1)
            long_begin = min(x_same_quantity)
            long_end = max(x_same_quantity)
            length = long_end-long_begin
            cost = quantity*length*self.available.cost_by_meter[abs(diameter*10)]/100

            new_bar = LongSteelBar(
                            long_begin=long_begin,
                            long_end=long_end,
                            quantity=quantity,
                            diameter=diameter,
                            quantity_accumulated = quantity_accumulated,
                            interspace=(interspace_start, interspace_end),
                            area = area,
                            area_accumulated = area_accumulated,
                            fyd = fyd,
                            length=length,
                            cost = cost
                            )
            print(new_bar)
            bars_interspace.add(new_bar)
            times_removal_occurred+=1

            if removal_limit_reached:
                break

    bars.add(bars_interspace)



[-11.99999 211.99999]
1
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
2
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
3
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
4
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
5
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
6
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
7
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
8
[-11.79978982 -11.59958964 -11.39938946 ... 211.39938946 211.59958964
 211.79978982]
[11. 11. 11. ... 11. 11. 11.]
[]
9
[-11.79978982 -1

In [46]:
quantity = 2

In [48]:

x_same_quantity = x_interspace[quantities_interspace == quantity]

In [50]:
quantities_interspace

array([11., 11., 11., ..., 11., 11., 11.])

In [ ]:
last_positive_bars = last_negative_bars = []
x_changes = []
for x in range(0, 1000):
    positive_bars, negative_bars = self.long_steel_bars.getPositiveandNegativeLongSteelBarsInX(x=x)
    positive_bars, negative_bars = positive_bars.steel_bars, negative_bars.steel_bars
    if not np.array_equal(positive_bars, last_positive_bars):
        x_changes = [*x_changes, x]
    elif not np.array_equal(negative_bars, last_negative_bars):
        x_changes = [*x_changes, x]
    last_positive_bars = positive_bars
    last_negative_bars = negative_bars
    
    
    

In [ ]:
for i in range(0, len(x_changes)-1):
    current_x = x_changes[i]
    next_x = x_changes[i+1]
    transversal_position = positive_bars.getBarTransversalPosition(self, x=(current_x+next_x)/2)
    _, y, _, area = transversal_position.T
    y_c = (y @ area)/sum(area)
    section.d = section.height - y_c
    self.beam_elements = self.beam_elements.split(next_x)
    
    
    

    

In [ ]:
beam_elements = []
nodes = self.beam_elements.nodes
for beam_element, i in zip(self.beam_elements, range(0,len(self.beam_elements)):
    beam_elements = 
    n1, n2 = self.beam_elements.nodes[i], self.beam_elements.nodes[i+1]
                           
    
    section, material = beam_element.section, beam_element.material
                           
    transversal_position = positive_bars.getBarTransversalPosition(self, x=(current_x+next_x)/2)
    _, y, _, area = transversal_position.T
    y_c = (y @ area)/sum(area)
    section.d = section.height - y_c
                           
    section.d =                  
    beam_elements = [*beam_elements, fc.BeamElement([n1, n2], section, material)]

In [ ]:
beam.long_steel_bars.plot()

In [ ]:
transversal_position = positive_bars.getBarTransversalPosition(self, x=500)
x, y, radius, area = transversal_position.T
x_c = (x @ area)/sum(area) #should be always 0
y_c = (y @ area)/sum(area)